test: &default

  # Credentials for REST APIs
  client_id: AQhjxxBXSoILi5-nBrq__M4oPb3JwTCJplRjGGLDCJ5Ua8p59UEnBZVGV-dM
  client_secret: EA5j3hAB6M9q75XRlGUWydH1Mvj4CUsddqvdCof3TX52douft2F3Bc1J1rDe

  # Mode can be 'live' or 'sandbox'
  mode: sandbox

  # Credentials for Classic APIs
  app_id: APP-80W284485P519543T
  username: jb-us-seller_api1.paypal.com
  password: WX4WTU3S8MY44S7F
  signature: AFcWxV21C7fd0v3bYYYRCpSSRl31A7yDhhsPUU2XhtMoZXsWHFxu-RWy
  # # With Certificate
  # cert_path: "config/cert_key.pem"
  sandbox_email_address: adelieonline-facilitator@gmail.com

  # # IP Address
  # ip_address: 127.0.0.1
  # # HTTP Proxy
  # http_proxy: http://proxy-ipaddress:3129/

development:
  <<: *default

production:
  <<: *default
  mode: live
